export const FOODS = Object.freeze({
    quinoa: "Quinoa",
    chia: "Chia seeds",
    halvedGreenPeas: "Halved green peas",
    wheyIsolate: "wheyIsolate",
    soyIsolate: "Soy isolate",
    whey: "Whey",
    banana: "Banana",
    flaxseeds: "Flaxseeds",
    celery: "Celery",
    spinach: "Spinach",
    cauliflower: "Cauliflower",
    broccoliFlorets: "Broccoli florets",
    naturjoghurt: "Naturjoghurt",
    speisequark: "Speisequark",
    soyMilk: "Soy milk",
    chickenBreast: "Chicken breast",
    mixedNuts: "Mixed nuts",
    cashews: "Cashews",
    walnuts: "Walnuts",
    eggs: "Eggs",
    berries: "Berries",
    apple: "Apple",
    oatFlakes: "Oat flakes",
    greenPeas: "Green peas",
    halvedYellowPeas: "Halved yellow peas",
    chickpeas: "Chickpeas",
    belugaLentils: "Beluga lentils",
    tofu: "Tofu",
    bergLinsen: "Berg linsen",
    roteLinsen: "Rote linsen",
    creatine: "Creatine",
    kakao: "Kakao",
    oliveOilExtra: "Olive oil extra",
    jungeErbsen: "Junge erbsen",
    hanfsamenRossamnn: "Hanfsamen rossamnn",
    leinsamenRossamnn: "Leinsamen rossamnn",
    chiasamenRossamnn: "Chiasamen rossamnn",
    spagehtti: "Spaghetti",
    thunfischfilets: "Thunfischfilets",
    maca: "Maca",
})